version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-php-fpm
        ports:
            - "8080:80"
            - "443:443"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
        environment:
            DATABASE_URL: postgresql://app:secret@manager-postgres:5432/app?serverVersion=13&charset=utf8
            MAILER_URL: smtp://mailer:1025
            REDIS_URL: tcp://manager-redis:6379?password=secret
        depends_on:
            - manager-postgres
            - manager-redis
            - mailer
    manager-php-cli:
        build:
            context: ./manager/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        environment:
            DATABASE_URL: postgresql://app:secret@manager-postgres:5432/app?serverVersion=13&charset=utf8

        depends_on:
            - manager-postgres
            - manager-redis
            - mailer
    manager-node-watch:
        image: node:16-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    manager-node:
        image: node:16-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
    manager-postgres:
        image: postgres:13-alpine
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
    manager-redis:
        image: redis:3.0-alpine
        volumes:
            - manager-redis:/data
        command: redis-server --requirepass secret
        ports:
            - "6380:6379"

    mailer:
        image: mailhog/mailhog
        ports:
            - "8081:8025"

volumes:
    manager-postgres:
    manager-redis:
    composer: