knpu_oauth2_client:
    clients:
        facebook_main:
            # must be "facebook" - it activates that type!
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # a route name you'll create
            redirect_route: oauth.facebook_check
            redirect_params: {}
            graph_api_version: v11.0

        facebook_attach:
            # must be "facebook" - it activates that type!
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # a route name you'll create
            redirect_route: profile.oauth.facebook_check
            redirect_params: {}
            graph_api_version: v11.0
